### ISSUE TITLE
关于无root情况下部分手机的提取方法

### ISSUE THREAD

**Issue by Janet-Baker** [HyperSine/forensic-qqtoken#8]
# 前提

- 系统需要内置一个“备份与重置”或类似应用。这个应用可能会在"设置"-"备份和重置"中，可能需要输入密码，可能强制加密。

- 准备好一台计算机。可能需要数据线、U盘、OTG设备等，用以转移备份好的文件。

# 通用的必要步骤

- 下载并安装 [Python 3](https://www.python.org/downloads/)

- 下载 [sqlite3](https://www.sqlite.org/download.html)

- 下载 [项目文件](https://github.com/HyperSine/forensic-qqtoken/archive/refs/heads/master.zip)

- `pip install cryptography`

# 特定系统的单独步骤

## 以 MIUI手机、Windows系统 为例，提取所需文件

- 下载 [Java](https://www.java.com/zh-CN/download/)

- 下载 [Android Backup Extracter](https://github.com/nelenkov/android-backup-extractor/releases)，我们需要的是 `abe.jar`

- 备份“QQ安全中心”

> 打开“设置”应用，点击"更多设置"-"备份和重置"-"本地备份"，输入密码(如果有)，点击"新建备份"，去掉所有的勾选，然后再点一下“软件程序”右侧的右箭头，选中"QQ安全中心"，点下方"确定"，点"开始备份"。

- 备份完成后，用各种方式、想方设法 将其转移到电脑上。

> 通常在`存储目录/MIUI/backup/AllBackup/日期时间`下。找到`QQ安全中心(com.tencent.token).bak`的那个文件，搞到电脑上。

- 处理`QQ安全中心(com.tencent.token).bak`

> 用记事本打开这个文件，将`ANDROID BACKUP`前面的内容全都删掉，改完后 `ANDROID BACKUP` 应该在第一行，保存并关闭。

- 将 处理过的`QQ安全中心(com.tencent.token).bak`、`abe.jar`放在同一个目录里（不放在一起也行，后面的指令看着命令行自己改）。

- 在当前目录打开命令提示符（不在当前目录打开也行，看着命令行自己改），输入 `java -jar abe.jar unpack 'QQ安全中心(com.tencent.token).bak' 'QQ安全中心(com.tencent.token).tar'`

- 打开`QQ安全中心(com.tencent.token).tar`，找到并解压`\apps\com.tencent.token\sp\token_save_info.xml`、`\apps\com.tencent.token\db\mobiletoken.db`，放在项目解压的文件夹里。

# 后续的相同步骤

- 按照项目说明，使用 `decrypt-database.py` 解密 `mobiletoken.db`

   ```
   Usage:
      decrypt-database.py <mobiletoken.db的路径>
   ```

   例如：

   ```
   python decrypt-database.py mobiletoken.db
   ```

- 查看加密的 `secret`：

   ```
   sqlite3 mobiletoken.db 
   SQLite version 3.28.0 2019-04-15 14:49:49
   Enter ".help" for usage hints.
   sqlite> select hex(data) from main.token_conf;
   AE28874351F682CFDD5263E3D71D74E7D8847F00D157923539811AD0920499B9A88A5B8021C1ED2E7B20BD597ADA33AE
   sqlite> exit()
   ```

   其中 `AE28874351F682CFDD5263E3D71D74E7D8847F00D157923539811AD0920499B9A88A5B8021C1ED2E7B20BD597ADA33AE` 就是加密的 `secret`。

- 解密出 `secret`：

   ```
   Usage:
       decrypt-secret.py <加密的secret> <加密secret的密钥>
   ```

   例如：

   ```
   python decrypt-secret.py AE28874351F682CFDD5263E3D71D74E7D8847F00D157923539811AD0920499B9A88A5B8021C1ED2E7B20BD597ADA33AE 14C27B6EC74543302F02C01B50E16ED7

   a42299e1ced4e705484392583ad0b76a8d6e893c2dd198bc399b4c9a4e3421eb
   ```

   其中 `a42299e1ced4e705484392583ad0b76a8d6e893c2dd198bc399b4c9a4e3421eb` 就是我们要找的 `secret`。

# 使用secret生成动态密码

```
Usage:
    generate-qqtoken.py <secret>
```

例如：

```
python generate-qqtoken.py a42299e1ced4e705484392583ad0b76a8d6e893c2dd198bc399b4c9a4e3421eb

530800
```

> 你可以考虑将这个命令保存为 批处理文件(.bat文件)，省去每次都要输入命令的麻烦。

**Comment by xja** [comment]
我的设备能够备份导出其它一些软件的数据，但是却不能导出QQ安全中心的软件数据，解压出来里面只有一个base.apk。不知道是系统还是软件的原因。
系统：MIUI 12.5.7
QQ安全中心版本：6.9.28
![.](https://i.imgur.com/mugX7Ym.png)

**Comment by callng** [comment]
@Janet-Baker 你好，请问你当时发布这个issues时使用的QQ安全中心版本是？现在这个项目不支持高版本(6.9.28)。

**Comment by Janet-Baker** [comment]
> 我的设备能够备份导出其它一些软件的数据，但是却不能导出QQ安全中心的软件数据，解压出来里面只有一个base.apk。不知道是系统还是软件的原因。 系统：MIUI 12.5.7 QQ安全中心版本：6.9.28 ![.](https://camo.githubusercontent.com/4862980d16a617d4be880a6bfed1802d67f460abaf47975cd583a7d807023bee/68747470733a2f2f692e696d6775722e636f6d2f6d75675837596d2e706e67)

我的MIUI10和11的系统内置的本地备份都可以导出完整的数据。MIUI12我也没用过。
你用的是“本地备份”并且选了“应用和数据”对吧？没用什么“云备份”或者“U盘备份”应该不会出现这种情况才对。

**Comment by Janet-Baker** [comment]
> @Janet-Baker 你好，请问你当时发布这个issues时使用的QQ安全中心版本是？现在这个项目不支持高版本(6.9.28)。

我写的时候已经很早了，用的还是6.9.17。
现在安全验证都不出现手机令牌的选项了……

**Comment by callng** [comment]
> 我写的时候已经很早了，用的还是6.9.17。 现在安全验证都不出现手机令牌的选项了……

好的，谢谢
