### ISSUE TITLE
不支持最新版本6.9.28

### ISSUE THREAD

**Issue by callng** [HyperSine/forensic-qqtoken#9]
安全中心版本： 6.9.28

**Comment by callng** [comment]
![就像这样](https://user-images.githubusercontent.com/64207250/189725377-1ff68053-4411-4550-8d35-91c2b1e297e6.png)

**Comment by Janet-Baker** [comment]
我还可以正常可以提取啊。
注意的是，如果要复制和移动文件的话，`mobiletoken.db`和`mobiletoken.db-journal`应该在一起。
（只不过generate-qqtoken.py给出的结果不对……这个得 @HyperSine 了）

**Comment by callng** [comment]
总体来说应该是算法和文件位置或者文件名变了

**Comment by HyperSine** [comment]
@callng 
可能吧。但是我倒是在想，这个forensic-qqtoken还有必要进行下去吗；因为我已经看到腾讯在逐渐抛弃这种动态密码，哪里还在用这种东西？aq.qq.com、找回密码、qq登录都看不到这种东西，再研究生成算法似乎没有什么意义了。

**Comment by callng** [comment]
@HyperSine 确实是这样，但是这种动态密码目前还能用于游戏的登录保护，常见于登录游戏(如lol)时要求填写动态密码，现在的盗号者很多，很多人不知道发生了什么账号就被盗走变成黑号。为了保险起见，我打开了登录动态密码验证。但是手机上再安装一个腾讯手机管家就显得有些多余了。

**Comment by callng** [comment]
我之前写了一个程序可以直接在我pc上运行实时显示账号的动态密码🤦，之前手贱绑定了一下腾讯手机管家上的令牌导致token失效了。

**Comment by HyperSine** [comment]
emm.. 好吧，我再看看

**Comment by callng** [comment]
> emm.. 好吧，我再看看

谢谢。

**Comment by callng** [comment]
由于开发者长久未回复，先暂时关闭这个议题

**Comment by Lua12138** [comment]
可以尝试下，继续安装旧版本，生成的令牌是否依旧可用。
